version: '3.8'

services:
  # Development Backend with hot reload
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - backend_cache:/app/__pycache__
    environment:
      - FASTAPI_ENV=development
      - DEBUG=true
    command: ["uvicorn", "server:app", "--reload", "--host", "0.0.0.0", "--port", "8001"]

  # Development Frontend with hot reload (Node.js 20.18.0)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - FAST_REFRESH=true
      - GENERATE_SOURCEMAP=true
      - REACT_APP_BACKEND_URL=http://localhost:8001
    command: ["npm", "start"]
    stdin_open: true
    tty: true

  # MongoDB for development
  mongodb:
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev123

volumes:
  backend_cache:
  frontend_node_modules: